In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from itertools import product

# --- funções de métricas hidrológicas ---
def rmse(observed, simulated):
    return np.sqrt(mean_squared_error(observed, simulated))

def nse(observed, simulated):
    """Nash–Sutcliffe Efficiency"""
    obs = np.array(observed)
    sim = np.array(simulated)
    return 1 - np.sum((obs - sim)**2) / np.sum((obs - np.mean(obs))**2)

def kge(observed, simulated):
    """Kling-Gupta Efficiency"""
    obs = np.array(observed)
    sim = np.array(simulated)
    r = np.corrcoef(obs, sim)[0,1]
    alpha = np.std(sim) / np.std(obs)
    beta  = np.mean(sim) / np.mean(obs)
    return 1 - np.sqrt((r-1)**2 + (alpha-1)**2 + (beta-1)**2)

def pbias(observed, simulated):
    """Percent Bias"""
    return 100.0 * np.sum(simulated - observed) / np.sum(observed)

# --- prepara features e target ---
def prepare_features(df, n_lags, n_ahead, use_monthly_mean):
    df = df.copy().sort_values('Data').reset_index(drop=True)
    df['month'] = df['Data'].dt.month

    # 1) dessazonalizar:
    if use_monthly_mean:
        split_idx = int(len(df) * 0.7)
        train_base = df.iloc[:split_idx]
        mens = train_base.groupby('month')['Vazao'].mean()
        df['Vazao'] = df['Vazao'] - df['month'].map(mens)

    # 2) gera lags e target a partir da série já dessazonalizada
    for lag in range(1, n_lags+1):
        df[f'lag_{lag}'] = df['Vazao'].shift(lag-1)
    df[f'y_{n_ahead}d'] = df['Vazao'].shift(-n_ahead)

    # 3) descarta NA, divide em treino/teste e extrai X/y
    cols_X = [f'lag_{lag}' for lag in range(1, n_lags+1)]
    df = df.dropna(subset=cols_X + [f'y_{n_ahead}d']).reset_index(drop=True)
    split_idx = int(len(df) * 0.7)
    df_train, df_test = df.iloc[:split_idx], df.iloc[split_idx:]

    X_train = df_train[cols_X].values
    y_train = df_train[f'y_{n_ahead}d'].values
    X_test  = df_test[cols_X].values
    y_test  = df_test[f'y_{n_ahead}d'].values

    # se precisar do vetor de média para reverter só no teste:
    vaz_med_test = None
    if use_monthly_mean:
        vaz_med_test = df_test['month'].map(mens).values

    return X_train, X_test, y_train, y_test, vaz_med_test




# --- loop de experimentos ---
def run_experiments(df):
    results = []
    opts_vaz = ['Sim', 'Não'] # = ['Sim', 'Não']
    opts_lags = [1, 7, 30] # = [1, 7, 30]
    opts_ahead = [1, 2, 7, 30] # = [1, 2, 7, 30]

    #callback do early stopping antes do loop (ou logo antes de treinar cada modelo)
    early_stop = tf.keras.callbacks.EarlyStopping(
        monitor='val_loss',
        patience=200,
        min_delta=1e-4,
        restore_best_weights=True)

    for vaz_opt, n_lags, n_ahead in product(opts_vaz, opts_lags, opts_ahead):
        use_mm = (vaz_opt == 'Sim')

        X_train, X_test, y_train, y_test, vaz_med = prepare_features(df, n_lags, n_ahead, use_mm)
        print(f"\n>>> n_ahead = {n_ahead}")
        print("y_test head:", y_test[:5])
        print("Primeiras 5 linhas de X_test:\n", X_test[:5, :])
        # escalonamento
        scaler = MinMaxScaler()
        X_train = scaler.fit_transform(X_train)
        X_test  = scaler.transform(X_test)

        # monta o modelo keras
        model = tf.keras.Sequential([
            tf.keras.layers.InputLayer(input_shape=(X_train.shape[1],)),
            tf.keras.layers.Dense(128, activation='relu'),
            tf.keras.layers.Dense(64, activation='relu'),
            tf.keras.layers.Dense(1)
        ])
        model.compile(optimizer='adam', loss='mse')

        #treina
        history = model.fit(
            X_train, y_train,
            epochs=625,
            batch_size=32,
            validation_split=0.2,
            callbacks=[early_stop],
            verbose=0
        )

        # extrai quantas épocas rodaram
        epochs_by_history = len(history.history['loss'])

        #previsao
        y_pred = model.predict(X_test).flatten()

        if use_mm== True:
            y_pred= y_pred+vaz_med
            y_test= y_test+vaz_med

        # métricas
        rmse_  = rmse(y_test, y_pred)
        nse_   = nse(y_test, y_pred)
        kge_   = kge(y_test, y_pred)
        pbias_ = pbias(y_test, y_pred)

        results.append({
            'vazao_menos_vaz_mensal_med': vaz_opt,
            'n_vazoes_anteriores':      n_lags,
            'n_dias_a_frente':          n_ahead,
            'RMSE':  rmse_,
            'NSE':   nse_,
            'KGE':   kge_,
            'Pbias': pbias_,
            'epochs':epochs_by_history
        })

        print(f'Concluído: mensal_med={vaz_opt}, lags={n_lags}, ahead={n_ahead}')

    return pd.DataFrame(results)

if __name__ == '__main__':
    #ler a série histórica
    #df = pd.read_csv('uniaoh.csv', parse_dates=['Data'])
    df = pd.read_csv('uniaoh.csv')
    df['Data'] = pd.to_datetime(df['Data'], format='%d/%m/%Y')

    resultados = run_experiments(df)
    resultados.to_csv('resultados_metricas.csv', index=False)
    print('Todos os cenários executados.')



>>> n_ahead = 1
y_test head: [-236.24216126 -254.44116126 -263.42516126 -260.43916126 -248.40916126]
Primeiras 5 linhas de X_test:
 [[-223.94416126]
 [-236.24216126]
 [-254.44116126]
 [-263.42516126]
 [-260.43916126]]


c:\Users\PersioPuertasGarciaL\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


297/297 ━━━━━━━━━━━━━━━━━━━━ 0s 467us/step
Concluído: mensal_med=Sim, lags=1, ahead=1

>>> n_ahead = 2
y_test head: [-236.24216126 -254.44116126 -263.42516126 -260.43916126 -248.40916126]
Primeiras 5 linhas de X_test:
 [[-202.11216126]
 [-223.94416126]
 [-236.24216126]
 [-254.44116126]
 [-263.42516126]]


c:\Users\PersioPuertasGarciaL\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


297/297 ━━━━━━━━━━━━━━━━━━━━ 0s 610us/step
Concluído: mensal_med=Sim, lags=1, ahead=2

>>> n_ahead = 7
y_test head: [-263.42516126 -260.43916126 -248.40916126 -263.42516126 -278.22316126]
Primeiras 5 linhas de X_test:
 [[-160.57416126]
 [-157.32716126]
 [-176.69916126]
 [-202.11216126]
 [-223.94416126]]


c:\Users\PersioPuertasGarciaL\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


297/297 ━━━━━━━━━━━━━━━━━━━━ 0s 473us/step
Concluído: mensal_med=Sim, lags=1, ahead=7

>>> n_ahead = 30
y_test head: [-321.21716126 -324.00416126 -326.78216126 -264.83856075 -275.88556075]
Primeiras 5 linhas de X_test:
 [[620.47906776]
 [616.11306776]
 [551.74083874]
 [525.82183874]
 [495.78683874]]


c:\Users\PersioPuertasGarciaL\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


296/296 ━━━━━━━━━━━━━━━━━━━━ 0s 494us/step
Concluído: mensal_med=Sim, lags=1, ahead=30

>>> n_ahead = 1
y_test head: [-263.42516126 -260.43916126 -248.40916126 -263.42516126 -278.22316126]
Primeiras 5 linhas de X_test:
 [[-254.44116126 -236.24216126 -223.94416126 -202.11216126 -176.69916126
  -157.32716126 -160.57416126]
 [-263.42516126 -254.44116126 -236.24216126 -223.94416126 -202.11216126
  -176.69916126 -157.32716126]
 [-260.43916126 -263.42516126 -254.44116126 -236.24216126 -223.94416126
  -202.11216126 -176.69916126]
 [-248.40916126 -260.43916126 -263.42516126 -254.44116126 -236.24216126
  -223.94416126 -202.11216126]
 [-263.42516126 -248.40916126 -260.43916126 -263.42516126 -254.44116126
  -236.24216126 -223.94416126]]


c:\Users\PersioPuertasGarciaL\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


297/297 ━━━━━━━━━━━━━━━━━━━━ 0s 682us/step
Concluído: mensal_med=Sim, lags=7, ahead=1

>>> n_ahead = 2
y_test head: [-263.42516126 -260.43916126 -248.40916126 -263.42516126 -278.22316126]
Primeiras 5 linhas de X_test:
 [[-236.24216126 -223.94416126 -202.11216126 -176.69916126 -157.32716126
  -160.57416126 -127.78716126]
 [-254.44116126 -236.24216126 -223.94416126 -202.11216126 -176.69916126
  -157.32716126 -160.57416126]
 [-263.42516126 -254.44116126 -236.24216126 -223.94416126 -202.11216126
  -176.69916126 -157.32716126]
 [-260.43916126 -263.42516126 -254.44116126 -236.24216126 -223.94416126
  -202.11216126 -176.69916126]
 [-248.40916126 -260.43916126 -263.42516126 -254.44116126 -236.24216126
  -223.94416126 -202.11216126]]


c:\Users\PersioPuertasGarciaL\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


297/297 ━━━━━━━━━━━━━━━━━━━━ 0s 513us/step
Concluído: mensal_med=Sim, lags=7, ahead=2

>>> n_ahead = 7
y_test head: [-248.40916126 -263.42516126 -278.22316126 -289.89816126 -312.79316126]
Primeiras 5 linhas de X_test:
 [[-176.69916126 -157.32716126 -160.57416126 -127.78716126  -80.74116126
    -4.29116126   -4.29116126]
 [-202.11216126 -176.69916126 -157.32716126 -160.57416126 -127.78716126
   -80.74116126   -4.29116126]
 [-223.94416126 -202.11216126 -176.69916126 -157.32716126 -160.57416126
  -127.78716126  -80.74116126]
 [-236.24216126 -223.94416126 -202.11216126 -176.69916126 -157.32716126
  -160.57416126 -127.78716126]
 [-254.44116126 -236.24216126 -223.94416126 -202.11216126 -176.69916126
  -157.32716126 -160.57416126]]


c:\Users\PersioPuertasGarciaL\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


297/297 ━━━━━━━━━━━━━━━━━━━━ 0s 586us/step
Concluído: mensal_med=Sim, lags=7, ahead=7

>>> n_ahead = 30
y_test head: [-324.00416126 -326.78216126 -264.83856075 -275.88556075 -278.62056075]
Primeiras 5 linhas de X_test:
 [[616.11306776 620.47906776 603.04006776 598.69106776 616.11306776
  637.98806776 646.76906776]
 [551.74083874 616.11306776 620.47906776 603.04006776 598.69106776
  616.11306776 637.98806776]
 [525.82183874 551.74083874 616.11306776 620.47906776 603.04006776
  598.69106776 616.11306776]
 [495.78683874 525.82183874 551.74083874 616.11306776 620.47906776
  603.04006776 598.69106776]
 [440.60483874 495.78683874 525.82183874 551.74083874 616.11306776
  620.47906776 603.04006776]]


c:\Users\PersioPuertasGarciaL\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


296/296 ━━━━━━━━━━━━━━━━━━━━ 0s 645us/step
Concluído: mensal_med=Sim, lags=7, ahead=30

>>> n_ahead = 1
y_test head: [-321.21716126 -324.00416126 -326.78216126 -264.83856075 -275.88556075]
Primeiras 5 linhas de X_test:
 [[-312.79316126 -289.89816126 -278.22316126 -263.42516126 -248.40916126
  -260.43916126 -263.42516126 -254.44116126 -236.24216126 -223.94416126
  -202.11216126 -176.69916126 -157.32716126 -160.57416126 -127.78716126
   -80.74116126   -4.29116126   -4.29116126   13.48883874  108.20883874
   225.76983874  276.46083874  332.64683874  390.37183874  440.60483874
   495.78683874  525.82183874  551.74083874  616.11306776  620.47906776]
 [-321.21716126 -312.79316126 -289.89816126 -278.22316126 -263.42516126
  -248.40916126 -260.43916126 -263.42516126 -254.44116126 -236.24216126
  -223.94416126 -202.11216126 -176.69916126 -157.32716126 -160.57416126
  -127.78716126  -80.74116126   -4.29116126   -4.29116126   13.48883874
   108.20883874  225.76983874  276.46083874  332.64683874  

c:\Users\PersioPuertasGarciaL\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


296/296 ━━━━━━━━━━━━━━━━━━━━ 0s 565us/step
Concluído: mensal_med=Sim, lags=30, ahead=1

>>> n_ahead = 2
y_test head: [-321.21716126 -324.00416126 -326.78216126 -264.83856075 -275.88556075]
Primeiras 5 linhas de X_test:
 [[-289.89816126 -278.22316126 -263.42516126 -248.40916126 -260.43916126
  -263.42516126 -254.44116126 -236.24216126 -223.94416126 -202.11216126
  -176.69916126 -157.32716126 -160.57416126 -127.78716126  -80.74116126
    -4.29116126   -4.29116126   13.48883874  108.20883874  225.76983874
   276.46083874  332.64683874  390.37183874  440.60483874  495.78683874
   525.82183874  551.74083874  616.11306776  620.47906776  603.04006776]
 [-312.79316126 -289.89816126 -278.22316126 -263.42516126 -248.40916126
  -260.43916126 -263.42516126 -254.44116126 -236.24216126 -223.94416126
  -202.11216126 -176.69916126 -157.32716126 -160.57416126 -127.78716126
   -80.74116126   -4.29116126   -4.29116126   13.48883874  108.20883874
   225.76983874  276.46083874  332.64683874  390.37183874  

c:\Users\PersioPuertasGarciaL\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


296/296 ━━━━━━━━━━━━━━━━━━━━ 0s 525us/step
Concluído: mensal_med=Sim, lags=30, ahead=2

>>> n_ahead = 7
y_test head: [-324.00416126 -326.78216126 -264.83856075 -275.88556075 -278.62056075]
Primeiras 5 linhas de X_test:
 [[-260.43916126 -263.42516126 -254.44116126 -236.24216126 -223.94416126
  -202.11216126 -176.69916126 -157.32716126 -160.57416126 -127.78716126
   -80.74116126   -4.29116126   -4.29116126   13.48883874  108.20883874
   225.76983874  276.46083874  332.64683874  390.37183874  440.60483874
   495.78683874  525.82183874  551.74083874  616.11306776  620.47906776
   603.04006776  598.69106776  616.11306776  637.98806776  646.76906776]
 [-248.40916126 -260.43916126 -263.42516126 -254.44116126 -236.24216126
  -223.94416126 -202.11216126 -176.69916126 -157.32716126 -160.57416126
  -127.78716126  -80.74116126   -4.29116126   -4.29116126   13.48883874
   108.20883874  225.76983874  276.46083874  332.64683874  390.37183874
   440.60483874  495.78683874  525.82183874  551.74083874  

c:\Users\PersioPuertasGarciaL\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


296/296 ━━━━━━━━━━━━━━━━━━━━ 0s 564us/step
Concluído: mensal_med=Sim, lags=30, ahead=7

>>> n_ahead = 30
y_test head: [-264.83856075 -210.20556075 -192.26356075 -201.27356075  -21.57556075]
Primeiras 5 linhas de X_test:
 [[ 276.46083874  332.64683874  390.37183874  440.60483874  495.78683874
   525.82183874  551.74083874  616.11306776  620.47906776  603.04006776
   598.69106776  616.11306776  637.98806776  646.76906776  499.90606776
   248.11606776   58.15606776 -314.68793224 -330.59693224 -309.29393224
  -298.37493224 -278.86293224 -267.49193224 -241.35093224 -223.51493224
  -211.44993224 -205.36593224 -208.41193224 -217.49893224 -220.51093224]
 [ 225.76983874  276.46083874  332.64683874  390.37183874  440.60483874
   495.78683874  525.82183874  551.74083874  616.11306776  620.47906776
   603.04006776  598.69106776  616.11306776  637.98806776  646.76906776
   499.90606776  248.11606776   58.15606776 -314.68793224 -330.59693224
  -309.29393224 -298.37493224 -278.86293224 -267.49193224 

c:\Users\PersioPuertasGarciaL\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


296/296 ━━━━━━━━━━━━━━━━━━━━ 0s 531us/step
Concluído: mensal_med=Sim, lags=30, ahead=30

>>> n_ahead = 1
y_test head: [261.129 242.93  233.946 236.932 248.962]
Primeiras 5 linhas de X_test:
 [[273.427]
 [261.129]
 [242.93 ]
 [233.946]
 [236.932]]


c:\Users\PersioPuertasGarciaL\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


297/297 ━━━━━━━━━━━━━━━━━━━━ 0s 530us/step
Concluído: mensal_med=Não, lags=1, ahead=1

>>> n_ahead = 2
y_test head: [261.129 242.93  233.946 236.932 248.962]
Primeiras 5 linhas de X_test:
 [[295.259]
 [273.427]
 [261.129]
 [242.93 ]
 [233.946]]


c:\Users\PersioPuertasGarciaL\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


297/297 ━━━━━━━━━━━━━━━━━━━━ 0s 575us/step
Concluído: mensal_med=Não, lags=1, ahead=2

>>> n_ahead = 7
y_test head: [233.946 236.932 248.962 233.946 219.148]
Primeiras 5 linhas de X_test:
 [[336.797]
 [340.044]
 [320.672]
 [295.259]
 [273.427]]


c:\Users\PersioPuertasGarciaL\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


297/297 ━━━━━━━━━━━━━━━━━━━━ 0s 586us/step
Concluído: mensal_med=Não, lags=1, ahead=7

>>> n_ahead = 30
y_test head: [176.154 173.367 170.589 173.367 162.32 ]
Primeiras 5 linhas de X_test:
 [[1083.92 ]
 [1079.554]
 [1049.112]
 [1023.193]
 [ 993.158]]


c:\Users\PersioPuertasGarciaL\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


296/296 ━━━━━━━━━━━━━━━━━━━━ 0s 541us/step
Concluído: mensal_med=Não, lags=1, ahead=30

>>> n_ahead = 1
y_test head: [233.946 236.932 248.962 233.946 219.148]
Primeiras 5 linhas de X_test:
 [[242.93  261.129 273.427 295.259 320.672 340.044 336.797]
 [233.946 242.93  261.129 273.427 295.259 320.672 340.044]
 [236.932 233.946 242.93  261.129 273.427 295.259 320.672]
 [248.962 236.932 233.946 242.93  261.129 273.427 295.259]
 [233.946 248.962 236.932 233.946 242.93  261.129 273.427]]


c:\Users\PersioPuertasGarciaL\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


297/297 ━━━━━━━━━━━━━━━━━━━━ 0s 481us/step
Concluído: mensal_med=Não, lags=7, ahead=1

>>> n_ahead = 2
y_test head: [233.946 236.932 248.962 233.946 219.148]
Primeiras 5 linhas de X_test:
 [[261.129 273.427 295.259 320.672 340.044 336.797 369.584]
 [242.93  261.129 273.427 295.259 320.672 340.044 336.797]
 [233.946 242.93  261.129 273.427 295.259 320.672 340.044]
 [236.932 233.946 242.93  261.129 273.427 295.259 320.672]
 [248.962 236.932 233.946 242.93  261.129 273.427 295.259]]


c:\Users\PersioPuertasGarciaL\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


297/297 ━━━━━━━━━━━━━━━━━━━━ 0s 536us/step
Concluído: mensal_med=Não, lags=7, ahead=2

>>> n_ahead = 7
y_test head: [248.962 233.946 219.148 207.473 184.578]
Primeiras 5 linhas de X_test:
 [[320.672 340.044 336.797 369.584 416.63  493.08  493.08 ]
 [295.259 320.672 340.044 336.797 369.584 416.63  493.08 ]
 [273.427 295.259 320.672 340.044 336.797 369.584 416.63 ]
 [261.129 273.427 295.259 320.672 340.044 336.797 369.584]
 [242.93  261.129 273.427 295.259 320.672 340.044 336.797]]


c:\Users\PersioPuertasGarciaL\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


297/297 ━━━━━━━━━━━━━━━━━━━━ 0s 527us/step
Concluído: mensal_med=Não, lags=7, ahead=7

>>> n_ahead = 30
y_test head: [173.367 170.589 173.367 162.32  159.585]
Primeiras 5 linhas de X_test:
 [[1079.554 1083.92  1066.481 1062.132 1079.554 1101.429 1110.21 ]
 [1049.112 1079.554 1083.92  1066.481 1062.132 1079.554 1101.429]
 [1023.193 1049.112 1079.554 1083.92  1066.481 1062.132 1079.554]
 [ 993.158 1023.193 1049.112 1079.554 1083.92  1066.481 1062.132]
 [ 937.976  993.158 1023.193 1049.112 1079.554 1083.92  1066.481]]


c:\Users\PersioPuertasGarciaL\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


296/296 ━━━━━━━━━━━━━━━━━━━━ 0s 535us/step
Concluído: mensal_med=Não, lags=7, ahead=30

>>> n_ahead = 1
y_test head: [176.154 173.367 170.589 173.367 162.32 ]
Primeiras 5 linhas de X_test:
 [[ 184.578  207.473  219.148  233.946  248.962  236.932  233.946  242.93
   261.129  273.427  295.259  320.672  340.044  336.797  369.584  416.63
   493.08   493.08   510.86   605.58   723.141  773.832  830.018  887.743
   937.976  993.158 1023.193 1049.112 1079.554 1083.92 ]
 [ 176.154  184.578  207.473  219.148  233.946  248.962  236.932  233.946
   242.93   261.129  273.427  295.259  320.672  340.044  336.797  369.584
   416.63   493.08   493.08   510.86   605.58   723.141  773.832  830.018
   887.743  937.976  993.158 1023.193 1049.112 1079.554]
 [ 173.367  176.154  184.578  207.473  219.148  233.946  248.962  236.932
   233.946  242.93   261.129  273.427  295.259  320.672  340.044  336.797
   369.584  416.63   493.08   493.08   510.86   605.58   723.141  773.832
   830.018  887.743  937.976  99

c:\Users\PersioPuertasGarciaL\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


296/296 ━━━━━━━━━━━━━━━━━━━━ 0s 483us/step
Concluído: mensal_med=Não, lags=30, ahead=1

>>> n_ahead = 2
y_test head: [176.154 173.367 170.589 173.367 162.32 ]
Primeiras 5 linhas de X_test:
 [[ 207.473  219.148  233.946  248.962  236.932  233.946  242.93   261.129
   273.427  295.259  320.672  340.044  336.797  369.584  416.63   493.08
   493.08   510.86   605.58   723.141  773.832  830.018  887.743  937.976
   993.158 1023.193 1049.112 1079.554 1083.92  1066.481]
 [ 184.578  207.473  219.148  233.946  248.962  236.932  233.946  242.93
   261.129  273.427  295.259  320.672  340.044  336.797  369.584  416.63
   493.08   493.08   510.86   605.58   723.141  773.832  830.018  887.743
   937.976  993.158 1023.193 1049.112 1079.554 1083.92 ]
 [ 176.154  184.578  207.473  219.148  233.946  248.962  236.932  233.946
   242.93   261.129  273.427  295.259  320.672  340.044  336.797  369.584
   416.63   493.08   493.08   510.86   605.58   723.141  773.832  830.018
   887.743  937.976  993.158 1023

c:\Users\PersioPuertasGarciaL\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


296/296 ━━━━━━━━━━━━━━━━━━━━ 0s 493us/step
Concluído: mensal_med=Não, lags=30, ahead=2

>>> n_ahead = 7
y_test head: [173.367 170.589 173.367 162.32  159.585]
Primeiras 5 linhas de X_test:
 [[ 236.932  233.946  242.93   261.129  273.427  295.259  320.672  340.044
   336.797  369.584  416.63   493.08   493.08   510.86   605.58   723.141
   773.832  830.018  887.743  937.976  993.158 1023.193 1049.112 1079.554
  1083.92  1066.481 1062.132 1079.554 1101.429 1110.21 ]
 [ 248.962  236.932  233.946  242.93   261.129  273.427  295.259  320.672
   340.044  336.797  369.584  416.63   493.08   493.08   510.86   605.58
   723.141  773.832  830.018  887.743  937.976  993.158 1023.193 1049.112
  1079.554 1083.92  1066.481 1062.132 1079.554 1101.429]
 [ 233.946  248.962  236.932  233.946  242.93   261.129  273.427  295.259
   320.672  340.044  336.797  369.584  416.63   493.08   493.08   510.86
   605.58   723.141  773.832  830.018  887.743  937.976  993.158 1023.193
  1049.112 1079.554 1083.92  106

c:\Users\PersioPuertasGarciaL\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


296/296 ━━━━━━━━━━━━━━━━━━━━ 0s 488us/step
Concluído: mensal_med=Não, lags=30, ahead=7

>>> n_ahead = 30
y_test head: [173.367 228.    245.942 236.932 416.63 ]
Primeiras 5 linhas de X_test:
 [[ 773.832  830.018  887.743  937.976  993.158 1023.193 1049.112 1079.554
  1083.92  1066.481 1062.132 1079.554 1101.429 1110.21   963.347  711.557
   521.597  148.753  132.844  154.147  165.066  184.578  195.949  222.09
   239.926  251.991  258.075  255.029  245.942  242.93 ]
 [ 723.141  773.832  830.018  887.743  937.976  993.158 1023.193 1049.112
  1079.554 1083.92  1066.481 1062.132 1079.554 1101.429 1110.21   963.347
   711.557  521.597  148.753  132.844  154.147  165.066  184.578  195.949
   222.09   239.926  251.991  258.075  255.029  245.942]
 [ 605.58   723.141  773.832  830.018  887.743  937.976  993.158 1023.193
  1049.112 1079.554 1083.92  1066.481 1062.132 1079.554 1101.429 1110.21
   963.347  711.557  521.597  148.753  132.844  154.147  165.066  184.578
   195.949  222.09   239.926  2

c:\Users\PersioPuertasGarciaL\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


296/296 ━━━━━━━━━━━━━━━━━━━━ 0s 488us/step
Concluído: mensal_med=Não, lags=30, ahead=30
Todos os cenários executados.


In [22]:
resultados

vazao_menos_vaz_mensal_med  n_vazoes_anteriores  n_dias_a_frente  \
0                         Sim                    1                1   
1                         Sim                    1                2   
2                         Sim                    1                7   
3                         Sim                    1               30   
4                         Sim                    7                1   
5                         Sim                    7                2   
6                         Sim                    7                7   
7                         Sim                    7               30   
8                         Sim                   30                1   
9                         Sim                   30                2   
10                        Sim                   30                7   
11                        Sim                   30               30   
12                        Não                    1                1   
13                        Não                    1                2   
14                        Não                    1                7   
15                        Não                    1               30   
16                        Não                    7                1   
17                        Não                    7                2   
18                        Não                    7                7   
19                        Não                    7               30   
20                        Não                   30                1   
21                        Não                   30                2   
22                        Não                   30                7   
23                        Não                   30               30   

          RMSE       NSE       KGE      Pbias  epochs  
0    67.109121  0.981349  0.989799   0.416217     625  
1   120.054436  0.940351  0.966351  -0.555785     625  
2   293.365218  0.644752  0.748228  -3.037348     625  
3   475.185130  0.050721  0.028165 -15.106114     318  
4    52.781198  0.988464  0.988619  -0.631119     323  
5    99.791296  0.958791  0.968594  -0.852537     529  
6   267.304225  0.705093  0.797446  -2.817022     625  
7   474.592151  0.053100  0.040523 -13.590626     576  
8    57.876095  0.986134  0.985712  -0.480243     297  
9   101.154919  0.957670  0.971080  -0.288789     329  
10  267.447444  0.704846  0.790118  -1.593180     379  
11  475.875688  0.048194  0.032843 -13.863100     358  
12   65.332737  0.982310  0.988812  -0.042564     625  
13  118.290947  0.942008  0.961707  -0.220535     329  
14  291.790159  0.647175  0.743957  -1.234816     342  
15  487.138682  0.016910 -0.015035 -16.651390     226  
16   48.396412  0.990294  0.994240   0.221058     497  
17   94.046964  0.963347  0.977730  -0.261328     598  
18  262.581813  0.714302  0.808051  -1.100427     625  
19  484.627095  0.027047  0.005329 -13.706111     502  
20   48.171647  0.990387  0.995053   0.108938     390  
21   94.353208  0.963119  0.978727  -0.262185     425  
22  261.577651  0.716549  0.805211  -0.024376     534  
23  484.602752  0.027288  0.001111 -12.356061     248